---
# file: roles/common/tasks/main.yml

- name: "add software-properties-common package (contains: apt-add-repository)"
  apt:
    name=software-properties-common
    state=latest
    update_cache=yes
  become: true

- name: "add ppa webupd8team/java (contains: java8)"
  shell: apt-add-repository ppa:webupd8team/java -y
  become: true

- name: accept Oracle license
  shell: "echo oracle-java{{ oracle_java_version }}-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections"
  changed_when: no
  become: true

- name: ensure Java is installed
  apt:
    name="oracle-java{{ oracle_java_version }}-installer"
    state={{ oracle_java_state }}
    update_cache=yes
  register: oracle_java_task_apt_install
  become: true

- name: set Java version as default
  apt:
    name="oracle-java{{ oracle_java_version }}-set-default"
    state=latest
  register: oracle_java_task_set_default
  when: oracle_java_set_as_default
  become: true
